name: Pulumi
on:
  - push
jobs:
  create-rds:
    name: Update
    runs-on: ubuntu-latest
    steps:
      # check out the infra code
      - uses: actions/checkout@v2
        with:
          repository: "mlibrodo/pulumi-test"
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev2  # somehow we need to init a new stack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
