name: Pulumi
on:
  - push
jobs:
  create-rds:
    name: Update
    runs-on: ubuntu-latest
    steps:
      # check out the infra code
      - uses: actions/checkout@v2
        with:
          repository: "mlibrodo/pulumi-test"
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev2  # somehow we need to init a new stack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ secrets.AWS_REGION }}

