name: Pulumi
on:
  - push
jobs:
  create-rds:
    name: Update
    runs-on: ubuntu-latest
    steps:
      # check out the infra code
      - uses: actions/checkout@v2
        with:
          repository: "mlibrodo/pulumi-test"
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev2  # somehow we need to init a new stack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
